version: '3'

services:

  website:
    image: alexvarney/habit-tracker:latest
    container_name: habit-tracker-node
    entrypoint: 'node /bin/www'
    ports:
      - "8000"   # Maps container port 80 to host port 8000
    environment:
      - NODE_ENV=production
      - PORT=80             # Internal port the app will run on
      - JWT_KEY=thisisabadidea
      - MONGO_HOST=mongodb://mongo:27017/candidate-dev
    volumes:
      - /mnt/electionsmaster/assets:/mnt/electionsmaster/assets
    networks:
      - app
    depends_on:
      - mongo               # Ensures MongoDB starts before this service

  mongo:
    image: mongo:3.4
    container_name: habit-tracker-mongodb
    expose:
      - "27017"             # Expose MongoDB's port for inter-service connection
    volumes:
      - /var/lib/mongodb:/data/db
    networks:
      - app

networks:
  app:
    driver: bridge           # Default network driver for internal communication
